# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# ORDER IS IMPORTANT FOR PROPER PARSING AND BUILDING

# Page Base
theme: jekyll-theme-so-simple
skin: "/assets/css/skins/dark.css"
destination: "./docs"
locale: en-US
title: "Marc Torres' Devlog"
baseurl: "/" # the subpath of your site, e.g. "/blog"
url: # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
logo: "/images/BongoFlyR.jpg" # path of site logo, e.g. "/assets/images/logo.png"

# Reading Config
date_format: "%d/%m/%Y"
read_time: true
words_per_minute: 150
mathjax:
  enable: true
#  combo: "tex-mml-chtml"
#  tags: "none"

# Media / Social / Google Config
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: # Google Analytics id, e.g. "UA-NNNNNNNN-N"
disqus:
  shortname: # Disqus shortname, e.g. "my_disqus_shortname"
twitter:
  username: MarcTorres_Dev # site's Twitter username

# Liquid
liquid:
  error_mode: strict

# Build settings
markdown: kramdown
feed:
  path: atom.xml

# Site Config
search_full_content: false
paginate: 5
paginate_path: /page:num/

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

# Collections
collections:
  recipes:
    output: true
    permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true

# Site Author
author:
  name: "Marc Torres Jimenez"
  picture: "/assets/images/BongoFly.jpg"
  email: 
  twitter: MarcTorres_Dev
  links:
    - title: Twitter
      url: https://twitter.com/MarcTorres_Dev
      icon: fas fa-twitter-square
    - title: Instagram
      url: https://instagram.com/MarcTorresDev
      icon: fas fa-instagram
    - title: Twitch
      url: https://twitch.tv/MarcTorres_Dev
      icon: fas fa-twitch-square

# Footer Links
test_var: true
footer_links:
  - title: Twitter
    url: https://twitter.com/MarcTorres_Dev
    icon: fab fa-twitter
  - title: Instagram
    url: https://instagram.com/MarcTorresDev
    icon: fab fa-instagram
  - title: GitHub
    url: https://github.com/MarcFly
    icon: fab fa-github
  - title: Twitch
    url: https://twitch.tv/MarcTorres_Dev
    icon: fab fa-twitch
